export interface LoginResponse {
  loginstatus: boolean
  isAdmin: boolean
  isGrand: boolean
  token: string
}

// Generated by https://quicktype.io

export interface ResponseUser {
  ma_cty: string
  ma_dl: string
  ten_dl: string
  email: string
  address?: string
  ngay_tham_gia: string
  tl_ck: number
  bac: number
  ngay_dau_ky: string
  doanh_so: number
  chiet_khau: number
  von: number
  loi_nhuan: number
}

export interface ResponseConfig {
  trang_thai: number
}
